# rule-lsass-credential-access.kql
# Credential Dumping Detection – LSASS Access (Mimikatz / Kiwi / Procdump)

(
  event.code: 10
  and winlog.event_data.TargetImage: "*\\lsass.exe"
  and winlog.event_data.CallTrace: "*mimikatz*"
)
or
(
  event.code: 4663
  and winlog.event_data.ObjectName: "*\\lsass.exe"
  and winlog.event_data.AccessMask: "0x1FFFFF"
)
or
(
  event.code: 4688
  and winlog.event_data.ProcessName: ("mimikatz.exe" or "procdump.exe" or "sqlmigrator.exe" or "*kiwi*")
)